[package]
name = "egui_qr"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.29.0", default-features = false }
qrcode = { version = "0.14.1", default-features = false }

[dev-dependencies]
eframe = "0.29.0"